export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  stock: number;
  sold: number;
}

export interface Order {
  id: string;
  productName: string;
  quantity: number;
  total: number;
  amountPaid: number;
  date: string;
  status: "completed" | "pending" | "cancelled";
  paymentType: "full" | "installment" | "unpaid";
  installmentPlan?: {
    totalInstallments: number;
    paidInstallments: number;
    installmentAmount: number;
  };
}

export interface Payment {
  id: string;
  orderId: string;
  amount: number;
  status: "successful" | "in-progress" | "failed";
  date: string;
  method: string;
  type: "full" | "installment";
  installmentNumber?: number;
  totalInstallments?: number;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: "admin" | "manager" | "staff";
  joinedDate: string;
}

export const initialProducts: Product[] = [
  {
    id: "P001",
    name: "Wireless Mouse",
    category: "Electronics",
    price: 29.99,
    stock: 150,
    sold: 342,
  },
  {
    id: "P002",
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    stock: 75,
    sold: 218,
  },
  {
    id: "P003",
    name: "USB-C Hub",
    category: "Accessories",
    price: 49.99,
    stock: 200,
    sold: 187,
  },
  {
    id: "P004",
    name: "Monitor Stand",
    category: "Furniture",
    price: 39.99,
    stock: 8,
    sold: 156,
  },
  {
    id: "P005",
    name: "Webcam HD",
    category: "Electronics",
    price: 69.99,
    stock: 120,
    sold: 294,
  },
  {
    id: "P006",
    name: "Desk Lamp",
    category: "Furniture",
    price: 24.99,
    stock: 5,
    sold: 98,
  },
  {
    id: "P007",
    name: "Mousepad XL",
    category: "Accessories",
    price: 19.99,
    stock: 300,
    sold: 412,
  },
  {
    id: "P008",
    name: "Cable Organizer",
    category: "Accessories",
    price: 14.99,
    stock: 3,
    sold: 67,
  },
  {
    id: "P009",
    name: "Laptop Stand",
    category: "Furniture",
    price: 54.99,
    stock: 90,
    sold: 178,
  },
  {
    id: "P010",
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 44.99,
    stock: 60,
    sold: 231,
  },
  {
    id: "P011",
    name: "Noise-Cancel Headphones",
    category: "Electronics",
    price: 129.99,
    stock: 45,
    sold: 310,
  },
  {
    id: "P012",
    name: "Ergonomic Chair",
    category: "Furniture",
    price: 299.99,
    stock: 12,
    sold: 89,
  },
  {
    id: "P013",
    name: "Wireless Charger",
    category: "Electronics",
    price: 34.99,
    stock: 180,
    sold: 256,
  },
  {
    id: "P014",
    name: "Screen Protector",
    category: "Accessories",
    price: 9.99,
    stock: 500,
    sold: 890,
  },
  {
    id: "P015",
    name: "Phone Holder",
    category: "Accessories",
    price: 15.99,
    stock: 220,
    sold: 345,
  },
  {
    id: "P016",
    name: "Standing Desk",
    category: "Furniture",
    price: 449.99,
    stock: 18,
    sold: 42,
  },
  {
    id: "P017",
    name: "HDMI Cable 2m",
    category: "Accessories",
    price: 12.99,
    stock: 350,
    sold: 567,
  },
  {
    id: "P018",
    name: "USB Flash Drive 64GB",
    category: "Electronics",
    price: 19.99,
    stock: 400,
    sold: 723,
  },
  {
    id: "P019",
    name: "Webcam Ring Light",
    category: "Accessories",
    price: 22.99,
    stock: 140,
    sold: 198,
  },
  {
    id: "P020",
    name: "External SSD 1TB",
    category: "Electronics",
    price: 89.99,
    stock: 55,
    sold: 167,
  },
  {
    id: "P021",
    name: "Desk Organizer Tray",
    category: "Furniture",
    price: 32.99,
    stock: 95,
    sold: 134,
  },
  {
    id: "P022",
    name: "Wrist Rest Pad",
    category: "Accessories",
    price: 18.99,
    stock: 210,
    sold: 278,
  },
  {
    id: "P023",
    name: "Smart Plug WiFi",
    category: "Electronics",
    price: 24.99,
    stock: 160,
    sold: 389,
  },
  {
    id: "P024",
    name: 'Portable Monitor 15"',
    category: "Electronics",
    price: 199.99,
    stock: 30,
    sold: 76,
  },
  {
    id: "P025",
    name: "Office Footrest",
    category: "Furniture",
    price: 44.99,
    stock: 70,
    sold: 112,
  },
];

export const initialOrders: Order[] = [
  {
    id: "ORD-001",
    productName: "Wireless Mouse",
    quantity: 2,
    total: 59.98,
    amountPaid: 59.98,
    date: "2026-02-09",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-002",
    productName: "Mechanical Keyboard",
    quantity: 1,
    total: 89.99,
    amountPaid: 89.99,
    date: "2026-02-08",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-003",
    productName: "USB-C Hub",
    quantity: 3,
    total: 149.97,
    amountPaid: 0,
    date: "2026-02-08",
    status: "pending",
    paymentType: "unpaid",
  },
  {
    id: "ORD-004",
    productName: "Monitor Stand",
    quantity: 1,
    total: 39.99,
    amountPaid: 39.99,
    date: "2026-02-07",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-005",
    productName: "Webcam HD",
    quantity: 2,
    total: 139.98,
    amountPaid: 0,
    date: "2026-02-07",
    status: "cancelled",
    paymentType: "unpaid",
  },
  {
    id: "ORD-006",
    productName: "Mousepad XL",
    quantity: 5,
    total: 99.95,
    amountPaid: 99.95,
    date: "2026-02-06",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-007",
    productName: "Bluetooth Speaker",
    quantity: 1,
    total: 44.99,
    amountPaid: 0,
    date: "2026-02-06",
    status: "pending",
    paymentType: "unpaid",
  },
  {
    id: "ORD-008",
    productName: "Noise-Cancel Headphones",
    quantity: 1,
    total: 129.99,
    amountPaid: 129.99,
    date: "2026-02-05",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-009",
    productName: "Ergonomic Chair",
    quantity: 1,
    total: 299.99,
    amountPaid: 100.0,
    date: "2026-02-05",
    status: "pending",
    paymentType: "installment",
    installmentPlan: {
      totalInstallments: 3,
      paidInstallments: 1,
      installmentAmount: 100.0,
    },
  },
  {
    id: "ORD-010",
    productName: "Standing Desk",
    quantity: 1,
    total: 449.99,
    amountPaid: 150.0,
    date: "2026-02-04",
    status: "pending",
    paymentType: "installment",
    installmentPlan: {
      totalInstallments: 3,
      paidInstallments: 1,
      installmentAmount: 150.0,
    },
  },
  {
    id: "ORD-011",
    productName: "External SSD 1TB",
    quantity: 2,
    total: 179.98,
    amountPaid: 179.98,
    date: "2026-02-04",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-012",
    productName: 'Portable Monitor 15"',
    quantity: 1,
    total: 199.99,
    amountPaid: 66.66,
    date: "2026-02-03",
    status: "pending",
    paymentType: "installment",
    installmentPlan: {
      totalInstallments: 3,
      paidInstallments: 1,
      installmentAmount: 66.66,
    },
  },
  {
    id: "ORD-013",
    productName: "Wireless Charger",
    quantity: 4,
    total: 139.96,
    amountPaid: 139.96,
    date: "2026-02-03",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-014",
    productName: "Smart Plug WiFi",
    quantity: 3,
    total: 74.97,
    amountPaid: 0,
    date: "2026-02-02",
    status: "pending",
    paymentType: "unpaid",
  },
  {
    id: "ORD-015",
    productName: "Desk Lamp",
    quantity: 2,
    total: 49.98,
    amountPaid: 49.98,
    date: "2026-02-02",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-016",
    productName: "Laptop Stand",
    quantity: 1,
    total: 54.99,
    amountPaid: 54.99,
    date: "2026-02-01",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-017",
    productName: "HDMI Cable 2m",
    quantity: 10,
    total: 129.9,
    amountPaid: 0,
    date: "2026-02-01",
    status: "pending",
    paymentType: "unpaid",
  },
  {
    id: "ORD-018",
    productName: "Screen Protector",
    quantity: 6,
    total: 59.94,
    amountPaid: 59.94,
    date: "2026-01-31",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-019",
    productName: "Wrist Rest Pad",
    quantity: 3,
    total: 56.97,
    amountPaid: 56.97,
    date: "2026-01-30",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-020",
    productName: "Office Footrest",
    quantity: 1,
    total: 44.99,
    amountPaid: 0,
    date: "2026-01-29",
    status: "cancelled",
    paymentType: "unpaid",
  },
  {
    id: "ORD-021",
    productName: "USB Flash Drive 64GB",
    quantity: 5,
    total: 99.95,
    amountPaid: 99.95,
    date: "2026-01-28",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-022",
    productName: "Webcam Ring Light",
    quantity: 2,
    total: 45.98,
    amountPaid: 0,
    date: "2026-01-27",
    status: "pending",
    paymentType: "unpaid",
  },
  {
    id: "ORD-023",
    productName: "Phone Holder",
    quantity: 4,
    total: 63.96,
    amountPaid: 63.96,
    date: "2026-01-26",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-024",
    productName: "Desk Organizer Tray",
    quantity: 2,
    total: 65.98,
    amountPaid: 65.98,
    date: "2026-01-25",
    status: "completed",
    paymentType: "full",
  },
  {
    id: "ORD-025",
    productName: "Cable Organizer",
    quantity: 8,
    total: 119.92,
    amountPaid: 40.0,
    date: "2026-01-24",
    status: "pending",
    paymentType: "installment",
    installmentPlan: {
      totalInstallments: 3,
      paidInstallments: 1,
      installmentAmount: 40.0,
    },
  },
];

export const initialPayments: Payment[] = [
  {
    id: "PAY-001",
    orderId: "ORD-001",
    amount: 59.98,
    status: "successful",
    date: "2026-02-09",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-002",
    orderId: "ORD-002",
    amount: 89.99,
    status: "successful",
    date: "2026-02-08",
    method: "PayPal",
    type: "full",
  },
  {
    id: "PAY-003",
    orderId: "ORD-004",
    amount: 39.99,
    status: "successful",
    date: "2026-02-07",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-004",
    orderId: "ORD-006",
    amount: 99.95,
    status: "successful",
    date: "2026-02-06",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-005",
    orderId: "ORD-008",
    amount: 129.99,
    status: "successful",
    date: "2026-02-05",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-006",
    orderId: "ORD-009",
    amount: 100.0,
    status: "successful",
    date: "2026-02-05",
    method: "Bank Transfer",
    type: "installment",
    installmentNumber: 1,
    totalInstallments: 3,
  },
  {
    id: "PAY-007",
    orderId: "ORD-010",
    amount: 150.0,
    status: "successful",
    date: "2026-02-04",
    method: "Credit Card",
    type: "installment",
    installmentNumber: 1,
    totalInstallments: 3,
  },
  {
    id: "PAY-008",
    orderId: "ORD-011",
    amount: 179.98,
    status: "successful",
    date: "2026-02-04",
    method: "Debit Card",
    type: "full",
  },
  {
    id: "PAY-009",
    orderId: "ORD-012",
    amount: 66.66,
    status: "successful",
    date: "2026-02-03",
    method: "Credit Card",
    type: "installment",
    installmentNumber: 1,
    totalInstallments: 3,
  },
  {
    id: "PAY-010",
    orderId: "ORD-013",
    amount: 139.96,
    status: "successful",
    date: "2026-02-03",
    method: "PayPal",
    type: "full",
  },
  {
    id: "PAY-011",
    orderId: "ORD-015",
    amount: 49.98,
    status: "successful",
    date: "2026-02-02",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-012",
    orderId: "ORD-016",
    amount: 54.99,
    status: "successful",
    date: "2026-02-01",
    method: "Debit Card",
    type: "full",
  },
  {
    id: "PAY-013",
    orderId: "ORD-018",
    amount: 59.94,
    status: "successful",
    date: "2026-01-31",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-014",
    orderId: "ORD-019",
    amount: 56.97,
    status: "successful",
    date: "2026-01-30",
    method: "PayPal",
    type: "full",
  },
  {
    id: "PAY-015",
    orderId: "ORD-021",
    amount: 99.95,
    status: "successful",
    date: "2026-01-28",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-016",
    orderId: "ORD-023",
    amount: 63.96,
    status: "successful",
    date: "2026-01-26",
    method: "Bank Transfer",
    type: "full",
  },
  {
    id: "PAY-017",
    orderId: "ORD-024",
    amount: 65.98,
    status: "successful",
    date: "2026-01-25",
    method: "Credit Card",
    type: "full",
  },
  {
    id: "PAY-018",
    orderId: "ORD-025",
    amount: 40.0,
    status: "successful",
    date: "2026-01-24",
    method: "Bank Transfer",
    type: "installment",
    installmentNumber: 1,
    totalInstallments: 3,
  },
];

export const initialUsers: User[] = [
  {
    id: "U001",
    name: "Alex Johnson",
    email: "alex@stockpilot.com",
    role: "admin",
    joinedDate: "2025-01-15",
  },
  {
    id: "U002",
    name: "Maria Santos",
    email: "maria@stockpilot.com",
    role: "manager",
    joinedDate: "2025-03-20",
  },
  {
    id: "U003",
    name: "David Kim",
    email: "david@stockpilot.com",
    role: "staff",
    joinedDate: "2025-06-10",
  },
  {
    id: "U004",
    name: "Sara Chen",
    email: "sara@stockpilot.com",
    role: "staff",
    joinedDate: "2025-08-05",
  },
  {
    id: "U005",
    name: "James Wilson",
    email: "james@stockpilot.com",
    role: "manager",
    joinedDate: "2025-09-12",
  },
];

export const dailySalesData = [
  { day: "Mon", sales: 42 },
  { day: "Tue", sales: 58 },
  { day: "Wed", sales: 35 },
  { day: "Thu", sales: 71 },
  { day: "Fri", sales: 89 },
  { day: "Sat", sales: 64 },
  { day: "Sun", sales: 47 },
];

export const monthlySalesData = [
  { month: "Aug", sales: 1200 },
  { month: "Sep", sales: 1450 },
  { month: "Oct", sales: 1320 },
  { month: "Nov", sales: 1680 },
  { month: "Dec", sales: 2100 },
  { month: "Jan", sales: 1890 },
  { month: "Feb", sales: 1560 },
];

export const clients = [
  {
    number: "+225 0565656657",
    name: "Bienvenu Ngadzie",
    totalOrder: 10,
    createdAt: "21.05.2023",
  },
  {
    number: "+225 0565656657",
    name: "Bienvenu Ngadzie",
    totalOrder: 10,
    createdAt: "21.05.2023",
  },
  {
    number: "+225 0565656657",
    name: "Bienvenu Ngadzie",
    totalOrder: 10,
    createdAt: "21.05.2023",
  },
  {
    number: "+225 0565656657",
    name: "Bienvenu Ngadzie",
    totalOrder: 10,
    createdAt: "21.05.2023",
  },
  {
    number: "+225 0565656657",
    name: "Bienvenu Ngadzie",
    totalOrder: 10,
    createdAt: "21.05.2023",
  },
  {
    number: "+225 0565656657",
    name: "Bienvenu Ngadzie",
    totalOrder: 10,
    createdAt: "21.05.2023",
  },
];
